### ISSUE TITLE
Bug: Metadata miswritten when Autorendering

### ISSUE THREAD

**Issue by Lisergishnu** [Jeff0S/sws#670]
Steps to reproduce bug:

1.- Set region a name including a diacritic (example *Programación*)
2.- Autorender the project

The filename will be ok but the metadata shows garbage where *ó* should be written. I think it's because the plugin doesn't properly read unicode. I looked the code and there was some Unicode macro commented out. Maybe if I'm given some general direction I could help solve this bug.

Cheers!

**Comment by Jeff0S** [comment]
Thanks for the report! Is this on Win or Mac?
Didn't tried on Win... but I've met the bug too while looking at something else...
=> fixed on OSX, at least.

**Comment by Jeff0S** [comment]
Yes, I guess this was on OSX because I couldn't duplicate on Win => closing the issue
