### ISSUE TITLE
SWS Ext. Freeze

### ISSUE THREAD

**Issue by facerecordings** [Jeff0S/sws#688]
Bring this issue to the proper place thanks to Jeffos.
Hi guys. I am running Reaper 4.7.6 on Mac OSX 10.9.2 16gigs ssd (quad 2.2 laptop.). SWS ver. 2.5.0 build #1. I am using reaper with about 12 tracks. Omnisphere, FM8, UAD CS-1, Guitar Rig, Massive, and Kontakt instance's spread across. Buffer setting 64. 44k. I am crashing when trying to recall snapshots. Everything worked before upgrading recently to Reaper 4.7.6 and SWS 2.5.0 build #1. I am doing a (Full Track Mix Recall) I get a spinning wheel forever. This used t work. Just wanted to shout out here and see if anyone can help. Reaper is amazing anyway. But I really want recall. ;^)
facerecordings is offline  	
_________________________________
Continued:
My system freezes,  just a spinning wheel.  Unfortunately, no crash report was generated.  I just updated to the new sWS Ext. to see if that might help.  It does not.  Same spinning wheel. I cannot enclose the .RPPfile as you suggested. Github will not allow.  I will post on the reaper forum thread for now.  We can continue here after post.

**Comment by facerecordings** [comment]
![screen shot 2015-01-07 at 11 52 05 am](https://cloud.githubusercontent.com/assets/10438684/5650779/114488de-9667-11e4-98dc-db77d70d12c2.png)
![screen shot 2015-01-07 at 12 16 28 pm](https://cloud.githubusercontent.com/assets/10438684/5650778/11430752-9667-11e4-8726-cd06ad756bf5.png)

**Comment by facerecordings** [comment]
Not sure how I can post the RPP file for you to look at.  Do you have an email?  Thanks

**Comment by Breeder** [comment]
You can upload it to http://stash.reaper.fm/ and give us the link here

**Comment by facerecordings** [comment]
http://stash.reaper.fm/22829/New%20Beginning.RPP[/url]

**Comment by facerecordings** [comment]
Trying to get this app to generate a crash log.  no dice so far.  I know it would help you.  Any ideas on how to get you the data you need?

**Comment by facerecordings** [comment]
I am happy to be a test dummy to get SWS Snapshots to work.  I own a tech company and have great skills with this stuff.  I truly love Reaper and the SWS stuff and want to master the use of Snapshots.  Thankyou SO much for your help.

**Comment by Jeff0S** [comment]
Closing this issue: there's long time I've fixed such snapshot crashes, and we don't any other report like that (and this Snapshot extension is quite popular...). Probably due to a buggy plug-in (?)
