### ISSUE TITLE
SWS Extensions-Live Config

### ISSUE THREAD

**Issue by Willo47** [Jeff0S/sws#689]
Hi,
Hans Heck here.
I have just loaded SWS extensions into Reaper with the intensions of using it for live config.
I have a midi keyboard which I drive a VST synth in reaper. I have numerous sound presets which I wish to change on the fly while playing, perfect for live config.
After the initial learning curve I have it going only to find out that the only way to move from one row to the next in live config requires a fader to be assigned giving CC commands.
It is impossible in a live situation to finely tune a fader to the correct row while you are playing a song. I have numerous switches (giving only 0 and 127) or pads which transmit program change commands. None of these switches are able to be used.
I have checked the Cockos forum and your issues list. There seems little info on the use of live config.
Any solutions to this?

Regards
Hans

**Comment by Jeff0S** [comment]
To deal with this myself I just copy/paste rows so that even a rough fader movement will do the job.
