### ISSUE TITLE
Note Window : Wrap Text doesn't work

### ISSUE THREAD

**Issue by X-Raym** [Jeff0S/sws#690]
Hi !
If I understand well, the Wrap Text option in the Note window has for purpose to force break lines if a line is too long.

But it doesn't seem to work.

I tested with both Reaper 4.76 SWS 2.6.0 #0 and Reaper 5 pre7 SWS 2.6.2 without success.

Did I make something wrong ?

**Comment by Jeff0S** [comment]
Not sure you gif has anything to do with this report...
I can confirm the wrap text option isn't working too well though, sometimes you might need to close/reopen the Notes window for this option to work. Will look at that...

**Comment by X-Raym** [comment]
Indeed, that was a poor copy pasting. My bad.

Thanks for your work on this :)

**Comment by Jeff0S** [comment]
fixed for the next pre-release (e7297be1ba12b2fa5df2d8a9949f050881876d2f)
