### ISSUE TITLE
Importing SRT subtitles - Region texts starts from the 2nd subtitle and after

### ISSUE THREAD

**Issue by sdancer75** [Jeff0S/sws#695]
This is a case ONLY when the first subtitle is starting from the very first beggining of the *.srt file (1st line of the text file).

Importing external *.srt subtitles, region text inside Cockos Reaper starts from the second subtitle and not from the first as it should be. 

Propably the internal code of the plugin, tries to find a LF/CR symbol to signal a new subtitle. 

Temporary solution : Just add a "blank line / Carriage return" in the first line of the SRT text file ( just before the 1st subtitle beggins ).

**Comment by sdancer75** [comment]
.... an adition rather a bug. It would be nice also to preview the next  subtitle besides the current one in the "notes" window to help the narrator to keep a steady voice tone.

**Comment by X-Raym** [comment]
You can use Heda's and mine scripts for subtitling, if you use REAPER pre-releases. It uses text items and not regions so you have more flexibility, at import, editing and export. Take a look at this:
http://forum.cockos.com/showthread.php?t=156423

**Comment by X-Raym** [comment]
Consider also using the Heda's Note Reader :P http://forum.cockos.com/showthread.php?t=155928

**Comment by Jeff0S** [comment]
I can't duplicate this neither on Win, nor in OSX.
Any additional details? Can you please link/attach such a faulty file? Thanks in advance.

**Comment by X-Raym** [comment]
I guess the original problem came from the SRT file. As far as I know, there is no such thing as SRT dialog lines without time code, and time code are before dialog lines, so text is never at the first line of the file.

**Comment by sdancer75** [comment]
Thanks I will give it a try !

**Comment by Jeff0S** [comment]
can't duplicate on win/osx, no feedback/attached example => closing

**Comment by chirick86** [comment]
You need save your srt file in UTF-8 WITHOUT BOM, and reaper import all lines include 1st

**Comment by X-Raym** [comment]
@chirick86 this case is closed since 2015 😆
