### ISSUE TITLE
Region Playlist seems to ignore automation on folder tracks

### ISSUE THREAD

**Issue by the3ug3reeder** [Jeff0S/sws#701]
I've been using the Region Playlist in reaper for a short time and so far i find it very useful...

one thing that seems to be not working properly is folder/empty tracks.
i use folders alot for creating submixes, and i put automation on these folders...

the easiest way to recreate the problem i'm having is:
1. create a new project
2. create a new track in the project
3. add a volume envelope and draw a bit of automation
4. create two regions whereever you want
5. create a region playlist using the two regions
6. use the Edit Project command to 'crop project to playlist'
-- reaper becomes unstable though it seems that nothing happened

If i have a Folder track with automation on it, the automation on my folder track gets ignored when i use the 'crop project to playlist' command.

i'm using REAPER v4.77/x64

Thanks for all the effort you've put into this already. I really appreciate it!
Cheers,
Lars

**Comment by Jeff0S** [comment]
Should be fixed in v2.7.1 (pre-release build)

**Comment by the3ug3reeder** [comment]
Great! Thank you very much Jeffos.where is it possible to download the beta?... also, would it be possible for me to install a beta build for testing purposes, and then reinstall the official release afterwards?
Cheers,Lars
 


     Jeff0S <notifications@github.com> schrieb am 17:56 Dienstag, 26.Mai 2015:
   

 Should be fixed in v2.7.1 (pre-release build)—

**Comment by Jeff0S** [comment]
I must say I didn't spend much time on this: so, yes, feedback is welcome!

BTW, thanks for the clear report Lars, that helped!

To download the latest beta, check out this link: http://forum.cockos.com/showpost.php?p=1460962&postcount=1 (download is intentionally "buried" now, to avoid confusions with official builds...). Please note this beta only works with REAPER 5, which is also in pre-release stage. So if you want to test things out but don't want to mess-up things you can do a *portable* install for v5 and install the SWS beta there.

**Comment by the3ug3reeder** [comment]
Thank you Jeffos!I'll install REAPER 5 beta for testing. 


     Jeff0S <notifications@github.com> schrieb am 9:50 Mittwoch, 27.Mai 2015:
   

 I must say I didn't spend much time on this: so, yes, feedback is welcome!BTW, thanks for the clear report Lars, that helped!To download the latest beta, check out this link: http://forum.cockos.com/showpost.php?p=1460962&postcount=1 (download is intentionally "buried" now, to avoid confusions with official builds...). Please note this beta only works with REAPER 5, which is also in pre-release stage. So if you want to test things out but don't want to mess-up things you can do a portable install for v5 and install the SWS beta there.—

**Comment by the3ug3reeder** [comment]
Hello Jeffos,

i've installed Reaper 5 now and also the latest SWS extensions and i can confirm that envelopes now seem to work well...
there's one thing i've noticed however:
when i use the "command crop project to playlist (new project tab)" the new project tab that gets created doesn't have the same BPM as the project that the original playlist was created from.
this seems to have some weird side effects even after setting the new project to the correct BPM.

cheers and thanks!
Lars
