### ISSUE TITLE
ULT_SetMediaItemNote not working in Lua

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [Jeff0S/sws#702]
im using Lua, SWS 2.6.1 with Reaper 5 pre 13.  I have also tested this with 5 pre 12, running SWS 2.6.1 and 2.6.2

If i create a new item with reaper.AddMediaItemToTrack() then attempt to run ULT_SetMediaItemNote() on it, nothing seems to happen, no notes are added.

**Comment by matthewjumpsoffbuildings** [comment]
just did a simple test

```lua
item = reaper.GetSelectedMediaItem(0, 0)

reaper.ULT_SetMediaItemNote(item, "test")
```

ran it on a single selected empty item, did nothing. is this function broken in Lua?

**Comment by Jeff0S** [comment]
Fixed for the next pre-release, thanks for the report.
Note about refresh: your script has to take care of it with UpdateArrange()
