### ISSUE TITLE
Linking errors when building on OSX 10.8.

### ISSUE THREAD

**Issue by roldugin** [Jeff0S/sws#704]
I'm trying to build SWS HEAD on OSX 10.8.2 with Xcode 5.1.

As documented in #584, I set the targets and SDK to 10.8 and the compiler to Apple LLVM 5.1.

I am compiling against `reaper_plugin_functions.h` from REAPER 4.77.

I also had to comment out `GetTrackDepth` function in `SnM_Track.cpp` since it is already provided by REAPER API since 4.5.

After that the compilation completes fine (through with 192 warnings!), but then I get a linker error for every function in REAPER API:

```
Ld sws_osx/reaper_sws.dylib normal i386
    cd /Users/grol/Dev/sws-extension/sws
    export MACOSX_DEPLOYMENT_TARGET=10.8
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -L/Users/grol/Dev/sws-extension/sws/sws_osx -L/Users/grol/Dev/sws-extension/sws/lib -F/Users/grol/Dev/sws-extension/sws/sws_osx -filelist /Users/grol/Dev/sws-extension/reaper_sws.build/Debug/reaper_sws.build/Objects-normal/i386/reaper_sws.LinkFileList -install_name /usr/local/lib/reaper_sws.dylib -mmacosx-version-min=10.8 -ltag -framework Cocoa -framework Carbon -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/grol/Dev/sws-extension/reaper_sws.build/Debug/reaper_sws.build/Objects-normal/i386/reaper_sws_dependency_info.dat -o /Users/grol/Dev/sws-extension/sws/sws_osx/reaper_sws.dylib

Undefined symbols for architecture i386:
  "_AddExtensionsMainMenu", referenced from:
      _ReaperPluginEntry in sws_extension.o
  "_AddMediaItemToTrack", referenced from:
      _ReaperPluginEntry in sws_extension.o
  ...
```

If I understand correctly, linking against those symbols should only happen at runtime when the extension is loaded by REAPER.

Am I missing a configuration step?

**Comment by Breeder** [comment]
https://github.com/Jeff0S/sws/commit/29e3f86379a9dc71bf6f81938d9449ef9cff8d16

So either use 4.75 or REAPER 5 pre-releases and branch "next". I would personally go for the latter, but things may still change since v5 is still unreleased...however, if those things do change and you work with 4.75 you will have to refix it for v5 at some point :)

**Comment by Breeder** [comment]
Btw, most of these warning are about deleting void* from WDL_PtrList and some unused variables...nothing of real importance (but I do agree that it's irritating to see...I personally don't use OSX except for testing so I never bothered to deal with it)

**Comment by roldugin** [comment]
Using 4.75 header worked, thank you.

Also the Xcode project was expecting `reaper_plugin_functions.h` in `/Applications` (I was placing it in `/<development root>/sws/reaper/` before).
