### ISSUE TITLE
FR: Resources window, project, open multiple projects at the same time

### ISSUE THREAD

**Issue by hedacoder** [Jeff0S/sws#709]
In the Resources window, in the projects list, or a bookmark, you can select multiple rows of projects, then right click, there are two options: Open and Open in new tab. but it only opens one of the selected project. **It would be nice if all selected rows are opened **

Also another enhancement, in the same window, when clicking in a row, in a comment to edit it, then you click inside the text to move the cursor, it unselects it, you have to move cursor with arrow keys. A bit unconvenient.

another FR would be to be able to add customized columns. like multiple comments columns for each project.

**Comment by hedacoder** [comment]
another small issue with the open (in new tab) from the Resources window is that it just creates a new tab and then opens the project there. Instead of directly opening the project into a new tab. The issue is that when creating the new tab, it loads the default template, and if you have a default template with many tracks, instruments or effects, it will take time to load the template, and then closes it to load the desired project.

**Comment by Jeff0S** [comment]
Both issues are fixed in v2.7.1
