### ISSUE TITLE
SWS v2.6.0 broken on PowerPC

### ISSUE THREAD

**Issue by Hypexed** [Jeff0S/sws#714]
I downloaded and installed SWS from the main page. I found there was the SWS menu missing in Reaoer. I checked to see if any rogue reaper_sws.dylib files were on my system and none were found. I then used the file command to check the file and it reported bad CPU type.

What's strange is that I had installed SWS earlier and it was in the menu. :-? I'm using Reaper V4.75 on a PowerBook G4 with OSX 10.5.8.

**Comment by Jeff0S** [comment]
Sorry for the trouble... Unfortunately I don't have any PPC to test :/
If you are enough motivated (and have some time to waste!), would you mind finding/telling me which was the last SWS "featured" (<- i.e. not a beta/pre-release) version working for you on PPC?

Older featured builds can be found here: http://sws.mj-s.com/download/featured/old/

Older older featured builds can be found here: https://code.google.com/p/sws-extension/downloads/list?can=3&q=&colspec=Filename+Summary+Uploaded+Size+DownloadCount

**Comment by Hypexed** [comment]
That should be easy. Just find the slight bigger file! :-)

Okay current older builds failed. But on odder older I got a hit!

v2.4.0 #1 OSX

Macintosh:~ Damien$ file /Volumes/SWS_Extension/reaper_sws.dylib 
/Volumes/SWS_Extension/reaper_sws.dylib: Mach-O universal binary with 3 architectures
/Volumes/SWS_Extension/reaper_sws.dylib (for architecture ppc):	Mach-O dynamically linked shared library ppc
/Volumes/SWS_Extension/reaper_sws.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/Volumes/SWS_Extension/reaper_sws.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64

**Comment by Hypexed** [comment]
Thanks for reply. That should be easy. Just find the slightly bigger file! :-)

Okay current older builds failed. But on older older I got a hit!
v2.4.0 #1 OSX

https://code.google.com/p/sws-extension/downloads/detail?name=sws_2.4.0.1.dmg&can=3&q=

Macintosh:~ Damien$ file /Volumes/SWS_Extension/reaper_sws.dylib 
/Volumes/SWS_Extension/reaper_sws.dylib: Mach-O universal binary with 3 architectures
/Volumes/SWS_Extension/reaper_sws.dylib (for architecture ppc): Mach-O dynamically linked shared library ppc
/Volumes/SWS_Extension/reaper_sws.dylib (for architecture i386): Mach-O dynamically linked shared library i386
/Volumes/SWS_Extension/reaper_sws.dylib (for architecture x86_64): Mach-O 64-bit dynamically linked shared library x86_64

**Comment by Jeff0S** [comment]
Thanks, I'm sorry but v2.4.0 #1 will be the last PPC build :/
