### ISSUE TITLE
Resource:Paste FX Chain to selected item, slot n

### ISSUE THREAD

**Issue by furkatbabadjanov** [Jeff0S/sws#734]
Reaper v.5.34, SWS 2.7.0
This function does not work correctly. Correct the bug. Here is the link:
https://cloud.mail.ru/public/2P4XZAz2LySc/Past%20FX-Chain.gif

**Comment by Jeff0S** [comment]
Sorry but this report is super vague, no idea of what the "bug" is supposed to be here (this gif is useless to me...). Please, at least provide your OS specs, and clear reproduction steps for your next reports (if any).

That been said, there is a general fix related to takes for the next build (v2.7.2), so may be it's already fixed... Well, let me know...

**Comment by furkatbabadjanov** [comment]
Thank you very much for your useful suggestions. It has been fixed in the next version(2.7.2) as you said.

**Comment by Jeff0S** [comment]
great, thanks for reporting back!
