### ISSUE TITLE
BR_GetMouseCursorContext crash REAPER 2.7.2

### ISSUE THREAD

**Issue by MichaelPilyavskiy** [Jeff0S/sws#740]
https://github.com/MichaelPilyavskiy/ReaScripts/blob/master/Useful_actions/mpl_Show_VSTi_on_track_under_mouse_cursor.eel 

2.7.1 - ok
2.7.2 - crash REAPER

**Comment by Breeder** [comment]
I presume all is good since you closed the issue?

**Comment by MichaelPilyavskiy** [comment]
Yes, it was broken in 5rc2. 5rc5 is ok
