### ISSUE TITLE
BR_SetTakeSourceFromFile2 - bug?

### ISSUE THREAD

**Issue by nounaim** [Jeff0S/sws#741]
Hi, I try to make script with this command, but reaper has Crashes with it 
& with BR_SetTakeSourceFromFile(1) too.
At first i just tried that & reaper was falled
item = GetSelectedMediaItem(0,0);
take = GetActiveTake(item);
extension_api("BR_SetTakeSourceFromFile2",take, "C:/snare.wav", 0, 1);
Config:reaper5rc6 x64/sws 2.7.2

**Comment by Breeder** [comment]
Please supply minimal example project and exact repro steps. Thanks.

**Comment by nounaim** [comment]
![setsource](https://cloud.githubusercontent.com/assets/8280029/8635062/4e8e9f5a-2824-11e5-9a4c-97bc2fa6185d.gif)
project - http://www.filedropper.com/brsettakesourcefromfile

**Comment by nounaim** [comment]
In 2.7.3 works correctly now ,Thank you for everything you do
