### ISSUE TITLE
BR_Env still crash Reaper

### ISSUE THREAD

**Issue by MichaelPilyavskiy** [Jeff0S/sws#742]
Hi, I wrote this script as request to make automation clip.
It should copy all points on multiple envelopes under some item and paste points to envelopes under items that pooled to selected item. It crashes Reaper. So is my script badly coded or there is a problem still?
 
https://github.com/MichaelPilyavskiy/ReaScripts/blob/master/Alpha/copy_automation_through_pooled_items_on_same_track

changelog 2.7.2
 "Hardened BR_Env functions so they don't crash REAPER in certain scenarios"

**Comment by Breeder** [comment]
Why not try and narrow the problem down when it happens in your script and make more simplified example?

**Comment by MichaelPilyavskiy** [comment]
Sorry, Breeder, it was my fault. I placed BR_EnvFree to wrong loop (now line 32). Now everything work, sorry again for that issue.
