### ISSUE TITLE
SWS: Crossfade adjacent selected items

### ISSUE THREAD

**Issue by daxliniere** [Jeff0S/sws#744]
I just discovered that this action actually MOVES the later item to crossfade with the previous item.

This behaviour should either;
1) be part of the action's name to warn the user, or
2) the later item's left edge should be extended to meet the previous item.

The current behaviour is quite dangerous as it messes with timing.

**Comment by Jeff0S** [comment]
Good call, thanks! Renamed this action for the next build.
