### ISSUE TITLE
BR_GetMouseCursorContext bug!!

### ISSUE THREAD

**Issue by nounaim** [Jeff0S/sws#745]
When i try to use this command, reaper just closes.
& when i try to run old script old scrip with this command i have a message stating that the reaper will be closed
It was ok in the previous reaper or sws version.
Config: Reaper5rc6 x64/sws 2.7.2
![bg](https://cloud.githubusercontent.com/assets/8280029/8705709/6b2c28ec-2b3c-11e5-9ff1-2d59c3197640.gif)

**Comment by nounaim** [comment]
i try sws 2.7.3, its ok, thanks

**Comment by Breeder** [comment]
Thanks for the report! Glad it turned out ok :)
Closing the issue.
