### ISSUE TITLE
Snapshot Visibility Bug

### ISSUE THREAD

**Issue by Poofox** [Jeff0S/sws#757]
Win7 x64
SWS 2.8.0 build 0

Problem: In certain situations visibility snapshots are saving/recalling custom filter options instead of track visibility.

Steps to reproduce:
1.  Open Snapshots and select any custom filter options
2.  Use action _SWSSNAPSHOT_VISMODE to switch to visibility mode
3.  Save new snapshot

Expected:  I've saved a new visibility snapshot

Actual Result:  I have actually saved a new custom snapshot with most recent custom settings

Why it's an issue:  I've been using cycle actions to switch between different sets of visible tracks.  Recently I noticed recalling these snapshots were sometimes undoing extensive mixing work instead of changing track visibility.  Finally noticed that it was because my "visibility" snapshots were actually custom snapshots, recalling various mix parameters, even between loading project sessions.

**Comment by Poofox** [comment]
Afaict, both the actions _SWSSNAPSHOT_MIXMODE and _SWSSNAPSHOT_VISMODE are broken.  They appear to change the mode in the Snapshot window, but new snapshots do not use the correct settings, instead using whichever options are checked (and greyed out) in the Filter under "Custom."

**Comment by Jeff0S** [comment]
Thanks for the detailed report Poofox (that helped!) , should be fixed in the next pre-release
