### ISSUE TITLE
BR_SetMediaTrackLayouts, graphical glitches

### ISSUE THREAD

**Issue by swiiscompos** [Jeff0S/sws#764]
With some layouts the API function BR_SetMediaTrackLayouts creates glitches. For example in the default theme, if you change the TCP layout to "bd --- Small Full Meter" and then back to the default layout, it will break the later.

**Comment by Breeder** [comment]
ReaScript documentation (Help->ReaScript documentation) clearly states:

```Note that in case of setting MCP layout, due to API limitations, MCP panel width is not updated to match the new layout. However, you can manually refresh it by calling the action "Mixer: Toggle master track visible" (just make sure to call it twice so master track visibility stays the same).```

Why is this expected from the user and not done directly when the API is called?
Because you may be changing layout of multiple tracks and that means that those actions would be called multiple times (for each call to BR_SetMediaTrackLayouts the actions would be called twice). Instead, user can simply call the action only 2 times, between setting all the layouts and thus not wasting CPU cycles on unneeded actions.

**Comment by swiiscompos** [comment]
But the problem happens with the TCP.

**Comment by Breeder** [comment]
I see now that you say TCP and not MCP. Sorry about that, I kinda misses it.
I guess you could employ the same trick but this time try and hide the track? I'll see if that works and I'll do it automatically in SWS for the next update.

**Comment by swiiscompos** [comment]
It does work, thanks!

**Comment by Breeder** [comment]
Ah, thanks for testing it for me then :) I'll push the fix now

**Comment by swiiscompos** [comment]
The MCP workaround is problematic for me because I'm using the function in a defer() script and it keeps changing the Master's visibility making the mixer useless. Any way to refresh the mcp panel width only when the layout is changed? Here is a post to Sexan's newest modification of my script: http://forum.cockos.com/showpost.php?p=1565504&postcount=5

**Comment by Breeder** [comment]
Function should return true if there were any changes so you can use that as the flag to refresh MCP with said actions

**Comment by swiiscompos** [comment]
Me again. I was able to avoid successfully the glitches but the use of hide/unhide (they have to be toggle to keep visibility state) makes the tcp and arrange view blink in a visible and quite annoying way. Is it going to be transparent when integrated in the function?

**Comment by Breeder** [comment]
Latest pre introduces additional API for track layouts. You can use that now. I'll fix SWS api so it also uses this new native API calss
