### ISSUE TITLE
Mouse Context Stretch Marker bugs

### ISSUE THREAD

**Issue by X-Raym** [Jeff0S/sws#765]
reaper.BR_GetMouseCursorContext() can return 'item_strech_marker" only if take playrate is 1, else it returns ITEM (except other special circumstances).

Consequences is that reaper.BR_GetMouseCursorContext_StretchMarker() often return -1 or nothing on strech marker on take with rate ~= 1.

You can test with https://github.com/X-Raym/REAPER-ReaScripts/blob/master/Items%20Properties/X-Raym_Reset%20stretch%20marker%20under%20mouse%20position.lua if you want !

**Comment by Breeder** [comment]
This should have been fixed for the last official build. Are you testing with latest SWS?

**Comment by X-Raym** [comment]
SWS 2.8.0 and REAPER 5.02 pre 1

https://monosnap.com/file/N094QqB2rRMnF4m2yDE03MJGM7TR9h.png

**Comment by X-Raym** [comment]
Hmm I'm confuse, it seems to work fine now despite the fact I didn't reinstall anything... I don't know what was wrong...
I'll test a bit  more and close the issue if I can't reproduce it at all...
Thanks for your support !

**Comment by X-Raym** [comment]
Ok I succeed to reproduce it
http://i.giphy.com/l41lLAiUQ1I8xFY7m.gif

**Comment by Breeder** [comment]
Can you share example project and explain exact repro steps?

**Comment by X-Raym** [comment]
1. Open project
2. Import my script https://github.com/X-Raym/REAPER-ReaScripts/blob/master/Items%20Properties/X-Raym_Reset%20stretch%20marker%20under%20mouse%20position.lua
3. Assign a keyboard shortcut
4. Try to make it work on the strech markers. Move strech markers and try again. => Sometimes it works, sometimes not.

If you want to do it by yourself
1. import an audio file in the project
2. add markers
3. change playrate to something a bit extreme such as x2, x3 or more.
4. use the action provided before.

**Comment by Breeder** [comment]
But does "sometimes it works, sometimes doesn't" happen consistently or what?
That's why I'm asking for example project - where it should be possible to consistently reproduce this :)

**Comment by X-Raym** [comment]
I updated a project in previous post. Two tracks : one with take at x2.7 and other at x1

I just close and reopen and REAPER and problem was still their for take at x2.7

**Comment by Breeder** [comment]
Ok, thanks - I'll check it out
