### ISSUE TITLE
SWS/BR can't make BR_Win32_GetPrivateProfileString work on OSX.

### ISSUE THREAD

**Issue by swiiscompos** [Jeff0S/sws#769]
I can't find how to make the BR_Win32_GetPrivateProfileString function work on my mac. Here is a small lua script that returns no value on my mac (layoutaction1 is defined in Reaper.ini)

 _, TCP_FolderLay    = reaper.BR_Win32_GetPrivateProfileString("REAPER", "layoutaction1", "", reaper.GetResourcePath().. "\\REAPER.ini")

**Comment by Breeder** [comment]
I can't test anything on OSX right now, but try replacing "\REAPER.ini" with "\\REAPER.ini" - yes, that's double slash.

**Comment by swiiscompos** [comment]
I don't know how it appeared with a single slash... but it's actually a double slash in my script. The single slash returns an error.

**Comment by Jeff0S** [comment]
On OSX, you have to use / not \
