### ISSUE TITLE
Problem with selecting non-folder tracks

### ISSUE THREAD

**Issue by ThoughtPhotography** [Jeff0S/sws#773]
Hello :)

I want an action that selects all non-folder tracks so I can lower the volume of all tracks to increase my headroom without changing the balance, and can't seem to get anything to work reliably.

I have a custom action that is "select all folders" + "toggle (invert) track selection", but that usually leaves me with folder tracks still selected. "Select all non-folders" sounds like it should do exactly what I want, but seems to give completely unexpected results (many non-folder tracks not selected).

Am I doing something wrong, or is there possibly a bug here?
(folder tracks are purple and teal)
http://i.imgur.com/tzfdzBn.gif

**Comment by highvoltaged** [comment]
I made a macro and it works every time for me:
SWS: Select all folder start tracks
SWS:Toggle (Invert) track seelection

Select all non-folders does nothing here also.

**Comment by ThoughtPhotography** [comment]
Ah yes! The parents were the problem. I had used those actions based on a recommendation, but it obviously wasn't the right one. Thanks :)
