### ISSUE TITLE
BR_GetMouseCursorContext_MIDI retval value

### ISSUE THREAD

**Issue by X-Raym** [Jeff0S/sws#783]
Hi,
According to the doc and to the previous scripts we already made, BR_GetMouseCursorContext_MIDI should return 
`
retval, inlineEditor, noteRow, ccLane, ccLaneVal, ccLaneId
`
It seems with REAPER 5.1 and SWS 2.8.2 that it now returns
`
inlineEditor, noteRow, ccLane, ccLaneVal, ccLaneId
`
and not matching with doc description.

More infos on this [thread](http://forum.cockos.com/showpost.php?p=1608277&postcount=5)

Tested in Lua on Windows 10.

Thanks for your support !

**Comment by X-Raym** [comment]
Maybe this is just an error in the doc.

**Comment by Jeff0S** [comment]
Should be fixed for the next build, note that the return value will be back...
Thanks for the detailed bug report, it helped.
