### ISSUE TITLE
SWS action "Set selected tracks MIDI input to...." no work

### ISSUE THREAD

**Issue by FastXeR** [Jeff0S/sws#788]
"Set selected tracks MIDI input to...." no work!
Cycle Action, it is necessary, on the selected track assign the midi channel.

**Comment by Jeff0S** [comment]
"Set selected tracks MIDI input to...." actions do work as expected here... Can you please attach a project demonstrating the issue (just the .RPP file) and tell me on which track the problem is supposed to occurs?
TIA

**Comment by FastXeR** [comment]
I figured out how it works. Thank you!
But I have not found a function that would change input the selected track. For example with mono:Left to midi Channel All.
