### ISSUE TITLE
Virus Warning by Download SWS 64bit

### ISSUE THREAD

**Issue by mdirecs** [Jeff0S/sws#792]
09.01.2016  14:30

downloading the 32bit via  "Download"-Button is OK

dowloading x64 via "Download"-Button --->  AVIRA Browser-Security-Alert ----> "Malware"

please fix this
![alert](https://cloud.githubusercontent.com/assets/16623376/12216340/35d0ffe6-b6de-11e5-8821-695ea4006864.jpg)

**Comment by X-Raym** [comment]
Confirmed

https://monosnap.com/file/DZUoB5Xl6siLdEyhCt0BG5ysXcpHNN.png

**Comment by Jeff0S** [comment]
Sorry for the trouble but this is an AVIRA issue (false positive detection), there's nothing we can do about it (apart reporting it, which I did...).

**Comment by Jeff0S** [comment]
Fast feedback from AVIRA, false positive confirmed: https://analysis.avira.com/en/status?uniqueid=6cF1VB2xhG6RfJr8JUUvMNrTbgIkdb1c&incidentid=1974009

I guess they will update their database soon...
