### ISSUE TITLE
BUG: Insert Marker At Play Cursor

### ISSUE THREAD

**Issue by daxliniere** [Jeff0S/sws#794]
SWS/S&M: Insert Marker At Play Cursor does not auto-increment anymore. Instead it inserts markers all with the same number as the last marker.

**Comment by Jeff0S** [comment]
Thanks for the report Dax! Confirmed w/ the following steps:
- add marker 1 & 2 with the said action
- remove marker 1
- re-add new markers with the said action
=> it inserts markers all with the same number as the last marker

It's a REAPER bug actually, so I'll fix it there (closing this SWS issue).

**Comment by Jeff0S** [comment]
Fixed in REAPER v5.12
